export const PERMISSIONS = {
    SUPERUSER: 'superuser',
    ADMIN: 'admin',
    IMPORT: 'import',
    REPORTS_VIEW: 'reports.view',

    ASSETS_VIEW: 'assets.view',
    ASSETS_CREATE: 'assets.create',
    ASSETS_EDIT: 'assets.edit',
    ASSETS_DELETE: 'assets.delete',
    ASSETS_CHECKOUT: 'assets.checkout',
    ASSETS_CHECKIN: 'assets.checkin',
    ASSETS_AUDIT: 'assets.audit',
    ASSETS_VIEW_REQUESTABLE: 'assets.view.requestable',
    ASSETS_VIEW_ENCRYPTED_CUSTOM_FIELDS: 'assets.view.encrypted_custom_fields',
    ASSETS_FILES: 'assets.files',

    ACCESSORIES_VIEW: 'accessories.view',
    ACCESSORIES_CREATE: 'accessories.create',
    ACCESSORIES_EDIT: 'accessories.edit',
    ACCESSORIES_DELETE: 'accessories.delete',
    ACCESSORIES_CHECKOUT: 'accessories.checkout',
    ACCESSORIES_CHECKIN: 'accessories.checkin',
    ACCESSORIES_FILES: 'accessories.files',

    CONSUMABLES_VIEW: 'consumables.view',
    CONSUMABLES_CREATE: 'consumables.create',
    CONSUMABLES_EDIT: 'consumables.edit',
    CONSUMABLES_DELETE: 'consumables.delete',
    CONSUMABLES_CHECKOUT: 'consumables.checkout',
    CONSUMABLES_FILES: 'consumables.files',

    LICENSES_VIEW: 'licenses.view',
    LICENSES_CREATE: 'licenses.create',
    LICENSES_EDIT: 'licenses.edit',
    LICENSES_DELETE: 'licenses.delete',
    LICENSES_CHECKOUT: 'licenses.checkout',
    LICENSES_CHECKIN: 'licenses.checkin',
    LICENSES_KEYS: 'licenses.keys',
    LICENSES_FILES: 'licenses.files',

    COMPONENTS_VIEW: 'components.view',
    COMPONENTS_CREATE: 'components.create',
    COMPONENTS_EDIT: 'components.edit',
    COMPONENTS_DELETE: 'components.delete',
    COMPONENTS_CHECKOUT: 'components.checkout',
    COMPONENTS_CHECKIN: 'components.checkin',
    COMPONENTS_FILES: 'components.files',

    KITS_VIEW: 'kits.view',
    KITS_CREATE: 'kits.create',
    KITS_EDIT: 'kits.edit',
    KITS_DELETE: 'kits.delete',

    USERS_VIEW: 'users.view',
    USERS_CREATE: 'users.create',
    USERS_EDIT: 'users.edit',
    USERS_DELETE: 'users.delete',
    USERS_FILES: 'users.files',

    MODELS_VIEW: 'models.view',
    MODELS_CREATE: 'models.create',
    MODELS_EDIT: 'models.edit',
    MODELS_DELETE: 'models.delete',
    MODELS_FILES: 'models.files',

    CATEGORIES_VIEW: 'categories.view',
    CATEGORIES_CREATE: 'categories.create',
    CATEGORIES_EDIT: 'categories.edit',
    CATEGORIES_DELETE: 'categories.delete',

    DEPARTMENTS_VIEW: 'departments.view',
    DEPARTMENTS_CREATE: 'departments.create',
    DEPARTMENTS_EDIT: 'departments.edit',
    DEPARTMENTS_DELETE: 'departments.delete',
    DEPARTMENTS_FILES: 'departments.files',

    STATUSLABELS_VIEW: 'statuslabels.view',
    STATUSLABELS_CREATE: 'statuslabels.create',
    STATUSLABELS_EDIT: 'statuslabels.edit',
    STATUSLABELS_DELETE: 'statuslabels.delete',

    CUSTOMFIELDS_VIEW: 'customfields.view',
    CUSTOMFIELDS_CREATE: 'customfields.create',
    CUSTOMFIELDS_EDIT: 'customfields.edit',
    CUSTOMFIELDS_DELETE: 'customfields.delete',

    SUPPLIERS_VIEW: 'suppliers.view',
    SUPPLIERS_CREATE: 'suppliers.create',
    SUPPLIERS_EDIT: 'suppliers.edit',
    SUPPLIERS_DELETE: 'suppliers.delete',
    SUPPLIERS_FILES: 'suppliers.files',

    MANUFACTURERS_VIEW: 'manufacturers.view',
    MANUFACTURERS_CREATE: 'manufacturers.create',
    MANUFACTURERS_EDIT: 'manufacturers.edit',
    MANUFACTURERS_DELETE: 'manufacturers.delete',

    DEPRECIATIONS_VIEW: 'depreciations.view',
    DEPRECIATIONS_CREATE: 'depreciations.create',
    DEPRECIATIONS_EDIT: 'depreciations.edit',
    DEPRECIATIONS_DELETE: 'depreciations.delete',

    LOCATIONS_VIEW: 'locations.view',
    LOCATIONS_CREATE: 'locations.create',
    LOCATIONS_EDIT: 'locations.edit',
    LOCATIONS_DELETE: 'locations.delete',
    LOCATIONS_FILES: 'locations.files',

    COMPANIES_VIEW: 'companies.view',
    COMPANIES_CREATE: 'companies.create',
    COMPANIES_EDIT: 'companies.edit',
    COMPANIES_DELETE: 'companies.delete',
    COMPANIES_FILES: 'companies.files',

    SELF_TWO_FACTOR: 'self.two_factor',
    SELF_API: 'self.api',
    SELF_EDIT_LOCATION: 'self.edit_location',
    SELF_CHECKOUT_ASSETS: 'self.checkout_assets',
    SELF_VIEW_PURCHASE_COST: 'self.view_purchase_cost',

    VIEW_SELECTLISTS: 'view.selectlists',
};
