export const PERMISSIONS = {
    SUPERUSER: 'superuser',
    ADMIN: 'admin',
    IMPORT: 'import',
    REPORTS_VIEW: 'reports.view',

    ASSETS_VIEW: 'assets.view',
    ASSETS_CREATE: 'assets.create',
    ASSETS_EDIT: 'assets.edit',
    ASSETS_DELETE: 'assets.delete',
    ASSETS_CHECKOUT: 'assets.checkout',
    ASSETS_CHECKIN: 'assets.checkin',
    ASSETS_AUDIT: 'assets.audit',
    ASSETS_VIEW_REQUESTABLE: 'assets.view.requestable',
    ASSETS_VIEW_ENCRYPTED_CUSTOM_FIELDS: 'assets.view.encrypted_custom_fields',
    ASSETS_FILES: 'assets.files',

    ACCESSORIES_VIEW: 'accessories.view',
    ACCESSORIES_CREATE: 'accessories.create',
    ACCESSORIES_EDIT: 'accessories.edit',
    ACCESSORIES_DELETE: 'accessories.delete',
    ACCESSORIES_CHECKOUT: 'accessories.checkout',
    ACCESSORIES_CHECKIN: 'accessories.checkin',
    ACCESSORIES_FILES: 'accessories.files',

    CONSUMABLES_VIEW: 'consumables.view',
    CONSUMABLES_CREATE: 'consumables.create',
    CONSUMABLES_EDIT: 'consumables.edit',
    CONSUMABLES_DELETE: 'consumables.delete',
    CONSUMABLES_CHECKOUT: 'consumables.checkout',
    CONSUMABLES_FILES: 'consumables.files',

    LICENSES_VIEW: 'licenses.view',
    LICENSES_CREATE: 'licenses.create',
    LICENSES_EDIT: 'licenses.edit',
    LICENSES_DELETE: 'licenses.delete',
    LICENSES_CHECKOUT: 'licenses.checkout',
    LICENSES_CHECKIN: 'licenses.checkin',
    LICENSES_KEYS: 'licenses.keys',
    LICENSES_FILES: 'licenses.files',

    COMPONENTS_VIEW: 'components.view',
    COMPONENTS_CREATE: 'components.create',
    COMPONENTS_EDIT: 'components.edit',
    COMPONENTS_DELETE: 'components.delete',
    COMPONENTS_CHECKOUT: 'components.checkout',
    COMPONENTS_CHECKIN: 'components.checkin',
    COMPONENTS_FILES: 'components.files',

    KITS_VIEW: 'kits.view',
    KITS_CREATE: 'kits.create',
    KITS_EDIT: 'kits.edit',
    KITS_DELETE: 'kits.delete',

    USERS_VIEW: 'users.view',
    USERS_CREATE: 'users.create',
    USERS_EDIT: 'users.edit',
    USERS_DELETE: 'users.delete',
    USERS_FILES: 'users.files',

    MODELS_VIEW: 'models.view',
    MODELS_CREATE: 'models.create',
    MODELS_EDIT: 'models.edit',
    MODELS_DELETE: 'models.delete',
    MODELS_FILES: 'models.files',

    CATEGORIES_VIEW: 'categories.view',
    CATEGORIES_CREATE: 'categories.create',
    CATEGORIES_EDIT: 'categories.edit',
    CATEGORIES_DELETE: 'categories.delete',

    DEPARTMENTS_VIEW: 'departments.view',
    DEPARTMENTS_CREATE: 'departments.create',
    DEPARTMENTS_EDIT: 'departments.edit',
    DEPARTMENTS_DELETE: 'departments.delete',
    DEPARTMENTS_FILES: 'departments.files',

    STATUSLABELS_VIEW: 'statuslabels.view',
    STATUSLABELS_CREATE: 'statuslabels.create',
    STATUSLABELS_EDIT: 'statuslabels.edit',
    STATUSLABELS_DELETE: 'statuslabels.delete',

    CUSTOMFIELDS_VIEW: 'customfields.view',
    CUSTOMFIELDS_CREATE: 'customfields.create',
    CUSTOMFIELDS_EDIT: 'customfields.edit',
    CUSTOMFIELDS_DELETE: 'customfields.delete',

    SUPPLIERS_VIEW: 'suppliers.view',
    SUPPLIERS_CREATE: 'suppliers.create',
    SUPPLIERS_EDIT: 'suppliers.edit',
    SUPPLIERS_DELETE: 'suppliers.delete',
    SUPPLIERS_FILES: 'suppliers.files',

    MANUFACTURERS_VIEW: 'manufacturers.view',
    MANUFACTURERS_CREATE: 'manufacturers.create',
    MANUFACTURERS_EDIT: 'manufacturers.edit',
    MANUFACTURERS_DELETE: 'manufacturers.delete',

    DEPRECIATIONS_VIEW: 'depreciations.view',
    DEPRECIATIONS_CREATE: 'depreciations.create',
    DEPRECIATIONS_EDIT: 'depreciations.edit',
    DEPRECIATIONS_DELETE: 'depreciations.delete',

    LOCATIONS_VIEW: 'locations.view',
    LOCATIONS_CREATE: 'locations.create',
    LOCATIONS_EDIT: 'locations.edit',
    LOCATIONS_DELETE: 'locations.delete',
    LOCATIONS_FILES: 'locations.files',

    COMPANIES_VIEW: 'companies.view',
    COMPANIES_CREATE: 'companies.create',
    COMPANIES_EDIT: 'companies.edit',
    COMPANIES_DELETE: 'companies.delete',
    COMPANIES_FILES: 'companies.files',

    SELF_TWO_FACTOR: 'self.two_factor',
    SELF_API: 'self.api',
    SELF_EDIT_LOCATION: 'self.edit_location',
    SELF_CHECKOUT_ASSETS: 'self.checkout_assets',
    SELF_VIEW_PURCHASE_COST: 'self.view_purchase_cost',

    VIEW_SELECTLISTS: 'view.selectlists',
};

export const PERMISSION_LABELS = {
    [PERMISSIONS.IMPORT]:                             'import data',
    [PERMISSIONS.REPORTS_VIEW]:                       'view reports',

    [PERMISSIONS.ASSETS_VIEW]:                        'view assets',
    [PERMISSIONS.ASSETS_CREATE]:                      'create assets',
    [PERMISSIONS.ASSETS_EDIT]:                        'edit assets',
    [PERMISSIONS.ASSETS_DELETE]:                      'delete assets',
    [PERMISSIONS.ASSETS_CHECKOUT]:                    'check out assets',
    [PERMISSIONS.ASSETS_CHECKIN]:                     'check in assets',
    [PERMISSIONS.ASSETS_AUDIT]:                       'audit assets',
    [PERMISSIONS.ASSETS_VIEW_REQUESTABLE]:            'view requestable assets',
    [PERMISSIONS.ASSETS_VIEW_ENCRYPTED_CUSTOM_FIELDS]:'view encrypted custom fields',
    [PERMISSIONS.ASSETS_FILES]:                       'manage asset files',

    [PERMISSIONS.ACCESSORIES_VIEW]:                   'view accessories',
    [PERMISSIONS.ACCESSORIES_CREATE]:                 'create accessories',
    [PERMISSIONS.ACCESSORIES_EDIT]:                   'edit accessories',
    [PERMISSIONS.ACCESSORIES_DELETE]:                 'delete accessories',
    [PERMISSIONS.ACCESSORIES_CHECKOUT]:               'check out accessories',
    [PERMISSIONS.ACCESSORIES_CHECKIN]:                'check in accessories',
    [PERMISSIONS.ACCESSORIES_FILES]:                  'manage accessory files',

    [PERMISSIONS.CONSUMABLES_VIEW]:                   'view consumables',
    [PERMISSIONS.CONSUMABLES_CREATE]:                 'create consumables',
    [PERMISSIONS.CONSUMABLES_EDIT]:                   'edit consumables',
    [PERMISSIONS.CONSUMABLES_DELETE]:                 'delete consumables',
    [PERMISSIONS.CONSUMABLES_CHECKOUT]:               'check out consumables',
    [PERMISSIONS.CONSUMABLES_FILES]:                  'manage consumable files',

    [PERMISSIONS.LICENSES_VIEW]:                      'view licenses',
    [PERMISSIONS.LICENSES_CREATE]:                    'create licenses',
    [PERMISSIONS.LICENSES_EDIT]:                      'edit licenses',
    [PERMISSIONS.LICENSES_DELETE]:                    'delete licenses',
    [PERMISSIONS.LICENSES_CHECKOUT]:                  'check out licenses',
    [PERMISSIONS.LICENSES_CHECKIN]:                   'check in licenses',
    [PERMISSIONS.LICENSES_KEYS]:                      'view license keys',
    [PERMISSIONS.LICENSES_FILES]:                     'manage license files',

    [PERMISSIONS.COMPONENTS_VIEW]:                    'view components',
    [PERMISSIONS.COMPONENTS_CREATE]:                  'create components',
    [PERMISSIONS.COMPONENTS_EDIT]:                    'edit components',
    [PERMISSIONS.COMPONENTS_DELETE]:                  'delete components',
    [PERMISSIONS.COMPONENTS_CHECKOUT]:                'check out components',
    [PERMISSIONS.COMPONENTS_CHECKIN]:                 'check in components',
    [PERMISSIONS.COMPONENTS_FILES]:                   'manage component files',

    [PERMISSIONS.KITS_VIEW]:                          'view kits',
    [PERMISSIONS.KITS_CREATE]:                        'create kits',
    [PERMISSIONS.KITS_EDIT]:                          'edit kits',
    [PERMISSIONS.KITS_DELETE]:                        'delete kits',

    [PERMISSIONS.USERS_VIEW]:                         'view users',
    [PERMISSIONS.USERS_CREATE]:                       'create users',
    [PERMISSIONS.USERS_EDIT]:                         'edit users',
    [PERMISSIONS.USERS_DELETE]:                       'delete users',
    [PERMISSIONS.USERS_FILES]:                        'manage user files',

    [PERMISSIONS.MODELS_VIEW]:                        'view asset models',
    [PERMISSIONS.MODELS_CREATE]:                      'create asset models',
    [PERMISSIONS.MODELS_EDIT]:                        'edit asset models',
    [PERMISSIONS.MODELS_DELETE]:                      'delete asset models',
    [PERMISSIONS.MODELS_FILES]:                       'manage asset model files',

    [PERMISSIONS.CATEGORIES_VIEW]:                    'view categories',
    [PERMISSIONS.CATEGORIES_CREATE]:                  'create categories',
    [PERMISSIONS.CATEGORIES_EDIT]:                    'edit categories',
    [PERMISSIONS.CATEGORIES_DELETE]:                  'delete categories',

    [PERMISSIONS.DEPARTMENTS_VIEW]:                   'view departments',
    [PERMISSIONS.DEPARTMENTS_CREATE]:                 'create departments',
    [PERMISSIONS.DEPARTMENTS_EDIT]:                   'edit departments',
    [PERMISSIONS.DEPARTMENTS_DELETE]:                 'delete departments',
    [PERMISSIONS.DEPARTMENTS_FILES]:                  'manage department files',

    [PERMISSIONS.STATUSLABELS_VIEW]:                  'view status labels',
    [PERMISSIONS.STATUSLABELS_CREATE]:                'create status labels',
    [PERMISSIONS.STATUSLABELS_EDIT]:                  'edit status labels',
    [PERMISSIONS.STATUSLABELS_DELETE]:                'delete status labels',

    [PERMISSIONS.CUSTOMFIELDS_VIEW]:                  'view custom fields',
    [PERMISSIONS.CUSTOMFIELDS_CREATE]:                'create custom fields',
    [PERMISSIONS.CUSTOMFIELDS_EDIT]:                  'edit custom fields',
    [PERMISSIONS.CUSTOMFIELDS_DELETE]:                'delete custom fields',

    [PERMISSIONS.SUPPLIERS_VIEW]:                     'view suppliers',
    [PERMISSIONS.SUPPLIERS_CREATE]:                   'create suppliers',
    [PERMISSIONS.SUPPLIERS_EDIT]:                     'edit suppliers',
    [PERMISSIONS.SUPPLIERS_DELETE]:                   'delete suppliers',
    [PERMISSIONS.SUPPLIERS_FILES]:                    'manage supplier files',

    [PERMISSIONS.MANUFACTURERS_VIEW]:                 'view manufacturers',
    [PERMISSIONS.MANUFACTURERS_CREATE]:               'create manufacturers',
    [PERMISSIONS.MANUFACTURERS_EDIT]:                 'edit manufacturers',
    [PERMISSIONS.MANUFACTURERS_DELETE]:               'delete manufacturers',

    [PERMISSIONS.DEPRECIATIONS_VIEW]:                 'view depreciation schedules',
    [PERMISSIONS.DEPRECIATIONS_CREATE]:               'create depreciation schedules',
    [PERMISSIONS.DEPRECIATIONS_EDIT]:                 'edit depreciation schedules',
    [PERMISSIONS.DEPRECIATIONS_DELETE]:               'delete depreciation schedules',

    [PERMISSIONS.LOCATIONS_VIEW]:                     'view locations',
    [PERMISSIONS.LOCATIONS_CREATE]:                   'create locations',
    [PERMISSIONS.LOCATIONS_EDIT]:                     'edit locations',
    [PERMISSIONS.LOCATIONS_DELETE]:                   'delete locations',
    [PERMISSIONS.LOCATIONS_FILES]:                    'manage location files',

    [PERMISSIONS.COMPANIES_VIEW]:                     'view companies',
    [PERMISSIONS.COMPANIES_CREATE]:                   'create companies',
    [PERMISSIONS.COMPANIES_EDIT]:                     'edit companies',
    [PERMISSIONS.COMPANIES_DELETE]:                   'delete companies',
    [PERMISSIONS.COMPANIES_FILES]:                    'manage company files',

    [PERMISSIONS.SELF_TWO_FACTOR]:                    'manage two-factor authentication',
    [PERMISSIONS.SELF_API]:                           'manage API tokens',
    [PERMISSIONS.SELF_EDIT_LOCATION]:                 'edit your location',
    [PERMISSIONS.SELF_CHECKOUT_ASSETS]:               'request assets',
    [PERMISSIONS.SELF_VIEW_PURCHASE_COST]:            'view purchase costs',

    [PERMISSIONS.VIEW_SELECTLISTS]:                   'view select lists',
};
