name: Crowdin Download

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  download-translations-from-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin pull
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          download_translations_args: '--exclude-language=aa'
          create_pull_request: true
          localization_branch_name: l10n_crowdin_translations
          pull_request_title: 'New Crowdin translations'
          pull_request_body: 'New translations pulled from Crowdin.'
          pull_request_base_branch_name: develop
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
